os:
- linux
services:
- docker
language: java
node_js:
- 4.5.0
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- java -version
script:
- "./mvnw clean"
- "./mvnw test"
- "./mvnw package -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: heroku
  api_key:
    secure: eY5BQuGZlouK+G8RFYqnQ3WO31LNNk4kM92dC/MqpkCRNpg+3KLxtnGFPu+M/CoLqC/nMMW2mZXF56mETMUiJ2Gys0Mb+sUxmlAtPosspFbcRbIPgDS1FFjLaAfpLyoHsCdcMkwA9f7Nmey8tABVia5p7FYmw7SQWZ1tebBjy8bYdXG5LZn3x1T+kdtaPgOQnukJFKe239KpjLHRJpB8npWdyTxcMNYU8+y1IJbySQdQCrmobTKcqKhvCHwxfgri8Id2nswhBjfz4G91IwITr+AJ3ZSPlxk9PhP413Hj1fHilgln262bn2ZSNSkG4XAIx2ib13hRDfugbcdRVGT/Y2pSMVXYGUFCAxN6Oo7sMmYan0FP3fhZUQ9eGp35fSheN66sSpqApRf7PPCkZx00JcZ0xE83OmMU6qQepn/7ZTp2eHmSgorI73HNx1cLLldQKSqhM4EIXWwvP+ZIAUQn0WNcHO2nvv+VcKMrCjTbr1F4AG2TNoFtwAraJGBfAAe97eHl/D01Io/UrFrgO9vuDTcHVffwlg7yaJtTO2XsC2XvXPNLTORuwLE3FxuAR5WdhuePcVNTRY146G9IvBKVVYQNmWUgDO1WHBzo0PpBuc0+0kiNWxdIrvhF/pbhG7tP9rkby5jjeLxvHYxh5L0f+uK0E3I2bMb1f44heGPtJgI=
  app: yaldaymerchant-staging-eu
  on:
    repo: Yalday/FinalYaldayMerchant
