version: '2'
services:
    finalyaldaymerchant-sonar:
        container_name: finalyaldaymerchant-sonar
        image: sonarqube:6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
